services:
  angolwords:
    build: .
    container_name: angolwords-app
    restart: unless-stopped
    environment:
      - PORT=3000
      - "DATABASE_URL=postgres://words_user:DFRGcdcscaasd432!@blog-db-1:5432/words_db"
    expose:
      - "3000"
    networks:
      - my-shared-network

networks:
  my-shared-network:
    external: true
